import type { Metadata } from 'next';
import SideBar from './_components/side-bar/side-bar';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* grid 레이아웃 이렇게 잡는게 좋을까? grid-template-areas 사용하려다 
          tailwind에서 지원하지 않는 것을 알게됨 */}
      <body className="min-w-screen min-h-screen grid grid-cols-6">
        <SideBar />
        {children}
      </body>
    </html>
  );
}
